# Generated by Django 4.2.19 on 2026-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, help_text="Указывать не обязательно", max_length=20, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Указывать не обязательно", max_length=35, verbose_name="Телефон"
            ),
        ),
    ]
