# Generated by Django 4.2.19 on 2026-06-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="Оглавление"),
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="Дата и время начала")),
                ("end_time", models.DateTimeField(verbose_name="Дата и время окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("running", "Запущена"), ("finished", "Завершена")],
                        default="created",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.message", verbose_name="Сообщение"
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(related_name="mailings", to="clients.client", verbose_name="Получатели"),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
