# Generated by Django 4.2.19 on 2026-06-18 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_message_body_alter_message_subject_mailing"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("server_response", models.TextField(blank=True, null=True, verbose_name="Ответ сервера / ошибка")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="clients.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client", verbose_name="Получатель"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог отправки",
                "verbose_name_plural": "Логи отправки",
            },
        ),
    ]
